# Generated by Django 2.1.3 on 2019-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_auto_20190519_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item_total',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='clientapp.Product'),
        ),
    ]
