# Generated by Django 2.1.3 on 2019-05-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymousreviews',
            old_name='anonymous_reviews',
            new_name='product',
        ),
    ]
