# Generated by Django 2.1.3 on 2019-04-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Product',
        ),
    ]
